### ISSUE TITLE
1.0.0 Master Checklist

### ISSUE THREAD

**Issue by brandonLi8** [brandonLi8/truenit#1]
# Top-level Master Checklist to be completed for 1.0.0:

## Design
- [ ] Design Document Created (Date: //)

## Implementation
- [x] Repository created (Date: 11/01/2019)
- [ ] License added (Date: //)
- [x] [Grunt Config](https://github.com/brandonLi8/grunt-config) Added
- [x] Github Project Roadmap completed (Date: 11/02/2019)
- [ ] Code Reviewer Identified and Completed (Date: //)
- [ ] Published! (Date: //)

## Grunt Config
- [x] `npm` initiated with `package.json` (Date: 11/02/2019)
- [x] GitHub labels added (Date: 11/02/2019)
- [ ] `README.md` created (Date: //)
- [x] `.gitignore` generated (Date: 11/02/2019)
- [ ] `travis.yml` generated and updated (Date: //)

## Testing
- [ ] Performance acceptable (Date: //)
- [ ] Feature Complete (Date: //)
